name: multitests
description: A platform created by 2.5 Perceivers and Adorkw to simplify the online tests, give them a nice and a simple interface, with amazing interpretations, colors and icons

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+22

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.3
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.5.2
  firebase_analytics: ^9.3.6
  firebase_analytics_platform_interface: ^3.3.5
  firebase_core: ^1.23.0
  firebase_core_platform_interface: ^4.5.1
  flutter:
    sdk: flutter
  go_router: ^5.0.2
  provider: ^6.0.3
  share_plus_dialog:
    git: https://github.com/2-5-perceivers/share_plus_dialog.git
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MultiIcons
      fonts:
        - asset: fonts/MultiIcons.ttf
