// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// flutterfire configure --project=multitests-d8913 --platforms=android,web,linux
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Rr58LHQ7S6YFC_oOLHq9FlZ1QtIlo9c',
    appId: '1:33701522106:web:a4861b94daff344c51f083',
    messagingSenderId: '33701522106',
    projectId: 'multitests-d8913',
    authDomain: 'multitests-d8913.firebaseapp.com',
    storageBucket: 'multitests-d8913.appspot.com',
    measurementId: 'G-PCCZDZRXDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1lnuekNxZ_s0a8SShztAno5t8ZnplfkY',
    appId: '1:33701522106:android:4fb0f3b31e7e175451f083',
    messagingSenderId: '33701522106',
    projectId: 'multitests-d8913',
    storageBucket: 'multitests-d8913.appspot.com',
  );
}
